// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZ1G5gZPECfyICaXyWomNU9CwEVo-32o',
    appId: '1:494630830510:web:e44b1b31b02b9345ba883f',
    messagingSenderId: '494630830510',
    projectId: 'jokesapplication-34c42',
    authDomain: 'jokesapplication-34c42.firebaseapp.com',
    storageBucket: 'jokesapplication-34c42.firebasestorage.app',
    measurementId: 'G-FCQ4NZ3JQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcnWwq20rFepIds0gudrNwoGYyLLL0ak',
    appId: '1:494630830510:android:ffa81037f8d2bdddba883f',
    messagingSenderId: '494630830510',
    projectId: 'jokesapplication-34c42',
    storageBucket: 'jokesapplication-34c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgYAgV_UnbaDAKPNJxyTu8mvBtods3Rk',
    appId: '1:494630830510:ios:dd47ea30c6a342e2ba883f',
    messagingSenderId: '494630830510',
    projectId: 'jokesapplication-34c42',
    storageBucket: 'jokesapplication-34c42.firebasestorage.app',
    iosBundleId: 'com.example.jokesApplicationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgYAgV_UnbaDAKPNJxyTu8mvBtods3Rk',
    appId: '1:494630830510:ios:dd47ea30c6a342e2ba883f',
    messagingSenderId: '494630830510',
    projectId: 'jokesapplication-34c42',
    storageBucket: 'jokesapplication-34c42.firebasestorage.app',
    iosBundleId: 'com.example.jokesApplicationFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZ1G5gZPECfyICaXyWomNU9CwEVo-32o',
    appId: '1:494630830510:web:5a4b4dc8c2c85015ba883f',
    messagingSenderId: '494630830510',
    projectId: 'jokesapplication-34c42',
    authDomain: 'jokesapplication-34c42.firebaseapp.com',
    storageBucket: 'jokesapplication-34c42.firebasestorage.app',
    measurementId: 'G-BGP0KG1BBE',
  );

}